name: Idea / feature request
description: Suggest an improvement or a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem or idea?
      description: What would you like to see, and why?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: How might it work?
      description: Any thoughts on how it could be done.
    validations:
      required: false
