---
# Install with: ansible-galaxy collection install -r ansible/requirements.yml
collections:
  - name: amazon.aws
    version: ">=11.3.0"
  - name: community.mysql
    version: ">=5.0.2"
  - name: community.proxysql
    version: ">=1.8.0"
