---
- ansible.builtin.import_tasks: install_proxysql.yml

- ansible.builtin.import_tasks: global_variables.yml

- ansible.builtin.import_tasks: database_hostgroups.yml

- ansible.builtin.import_tasks: database_hosts.yml

- ansible.builtin.import_tasks: database_users.yml
